import { ControlBarUI } from '../../src/content/control-bar/ui.js';
import { ControlBarStateStore } from '../../src/content/control-bar/state.js';
const calls: any[] = [], requests: any[] = [];
(globalThis as any).chrome = { storage: {local: {get: (_: any, cb: any) => cb({}), set: () => Promise.resolve()}}, runtime: { sendMessage: (message: any, cb: any) => { calls.push(message); if(cb) requests.push(cb); return Promise.resolve(); } } };
const check = (ok: any, message: string) => { if(!ok) throw Error(message); };
async function run() {
try {
const store = new ControlBarStateStore();
const ui = new ControlBarUI(store);
const queue = Array.from({length: 20}, (_, i) => ({videoId: `v${i}`, title:`Song ${i}`, channel:'Artist', url:`https://www.youtube.com/watch?v=v${i}`, isCurrent:i===0, durationText:'3:00'}));
const state: any = {videoId:'v0',title:'Song 0',channel:'Artist',currentTime:1,duration:180,isPlaying:true,volume:50,isMuted:false,hasNext:true,hasPrevious:true,queue,queueAvailable:true,availableQualities:[],lastUpdated:Date.now()};
store.update(state, []);
const root = document.querySelector('yt-global-control-bar')!.shadowRoot!;
const el = (selector: string) => root.querySelector(selector) as HTMLElement;
el('.queue-btn').click();
const row = el('.queue-item');
row.focus();
el('.queue-list').scrollTop = 180;
for(let i=0;i<100;i++) store.update({...state,currentTime:i},[]);
check(el('.queue-item')===row,'Queue replaced during playback updates');
check(el('.queue-list').scrollTop===180,'Queue scroll position lost');
check(root.activeElement===row,'Queue focus lost');
const beforeQueue = calls.length;
(root.querySelectorAll('.queue-item')[1] as HTMLElement).click();
check(calls.length === beforeQueue + 1, 'Queue selection sent extra playback commands');
check(calls.at(-1).type === 'PLAY_QUEUE_ITEM' && calls.at(-1).payload.videoId === 'v1' && calls.at(-1).payload.url === queue[1].url, 'Queue played the wrong selection');
const filter = el('.queue-filter') as HTMLInputElement;
filter.value='Song 19';filter.dispatchEvent(new Event('input'));
check(root.querySelectorAll('.queue-item').length===1,'Queue filtering failed');
el('.queue-current-btn').click();
check(root.querySelectorAll('.queue-item').length===20,'Now playing did not reset filter');
el('.search-btn').click();
const input = el('.search-text-input') as HTMLInputElement;
const search = (value:string) => {input.value=value; input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));};
search('old');search('new');
const result = (title:string) => ({success:true,data:[{title,videoId:title,url:'https://www.youtube.com/watch?v=x',thumbnailUrl:'',channel:'Artist'}]});
requests[1](result('Newest'));requests[0](result('Outdated'));
check(el('.search-results-list').textContent!.includes('Newest') && !el('.search-results-list').textContent!.includes('Outdated'),'Stale search response overwrote results');
input.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));
check(root.activeElement===el('.search-result-card'),'Keyboard navigation failed');
const beforeSearchPlay = calls.length;
el('.search-result-card').click();
check(calls.length === beforeSearchPlay + 1 && calls.at(-1).type === 'PLAY_QUEUE_ITEM' && calls.at(-1).payload.videoId === 'Newest', 'Search selection sent incorrect or extra playback commands');
el('.search-btn').click();
search('clear');el('.search-clear-btn').click();requests[2](result('Must not appear'));
check(!el('.search-results-list').textContent!.includes('Must not appear'),'Cleared search repopulated');
search('error');requests[3]({success:false,error:'Offline'});
check(el('.search-results-list').textContent!.includes('Retry search'),'Retry missing');
el('.search-cut-btn').click();
check(root.activeElement===el('.search-btn'),'Search focus not restored');
el('.preview-toggle-btn').click();
const resize = el('.preview-resize-handle');
const preview = el('.video-preview-window');
const original = preview.getBoundingClientRect();
resize.dispatchEvent(new KeyboardEvent('keydown', {key: 'ArrowRight', bubbles: true}));
check(preview.getBoundingClientRect().width === original.width + 10, 'Preview resize failed');
check(JSON.parse(localStorage.getItem('yt_preview_size')!).width === original.width + 10, 'Preview size not saved');
for (let i = 0; i < 100; i++) {
  resize.dispatchEvent(new KeyboardEvent('keydown', {key: 'ArrowRight', shiftKey: true, bubbles: true}));
  resize.dispatchEvent(new KeyboardEvent('keydown', {key: 'ArrowDown', shiftKey: true, bubbles: true}));
}
const enlarged = preview.getBoundingClientRect();
check(enlarged.right <= innerWidth - 7 && enlarged.bottom <= innerHeight - 7 && enlarged.left >= 8 && enlarged.top >= 8, 'Resized preview exceeds viewport');
resize.dispatchEvent(new MouseEvent('dblclick', {bubbles: true}));
check(preview.getBoundingClientRect().width === 360 && preview.getBoundingClientRect().height === 210, 'Preview reset failed');
const beforeFocus = calls.length;
el('.preview-fullscreen-btn').click();
el('.preview-open-yt').click();
check(calls.length === beforeFocus + 2 && calls.slice(beforeFocus).every(call => call.type === 'FOCUS_YOUTUBE_TAB'), 'Preview links must focus the existing YouTube tab');
store.update({...state, isPlaying: false}, []);
check(getComputedStyle(el('.preview-controls-overlay')).opacity === '0', 'Paused preview controls visible without hover');
store.update(state, []);
const beforePrevious = calls.length;
el('.preview-prev-track').click();
check(calls.length === beforePrevious + 1 && calls.at(-1).type === 'PREVIOUS', 'Previous command duplicated or incorrect');
store.update({...state, videoId: 'v1'}, []);
const beforeNext = calls.length;
el('.preview-next-track').click();
check(calls.length === beforeNext + 1 && calls.at(-1).type === 'NEXT', 'Next command duplicated or incorrect');
const top=el('.preview-top-bar').getBoundingClientRect(), mid=el('.preview-center-controls').getBoundingClientRect(), bottom=el('.preview-bottom-bar').getBoundingClientRect();
check(top.bottom<=mid.top+1 && mid.bottom<=bottom.top+1,'Preview control rows overlap');
store.update(state, []);
const beforeLike=calls.length;
el('.like-btn').click();
check(calls.slice(beforeLike).filter(c=>c.type==='TOGGLE_LIKE').length===1,'Like toggled twice');
check(el('.like-btn').classList.contains('liked') && el('.like-btn').classList.contains('pop-anim'),'Like animation missing');
store.update({...state,isLiked:false},[]);
check(el('.like-btn').classList.contains('liked'),'Stale state reset optimistic like');
el('.like-btn').click();
check(!el('.like-btn').classList.contains('liked') && el('.like-btn').classList.contains('unlike-anim'),'Unlike animation missing');
for (const [selector,delta] of [['.skip-back-btn',-10],['.skip-fwd-btn',10]] as const) {
check(root.querySelectorAll(selector).length===1,'Duplicate skip button');
check(getComputedStyle(el(selector)).display!=='none','Skip button hidden');
el(selector).click(); check(calls.at(-1).payload.delta===delta,'Skip command incorrect');
}
const dock = el('.bar-container');
const host = document.querySelector('yt-global-control-bar')!;
el('.hide-btn').click();
const retract = dock.getAnimations()[0];
check(!!retract, 'Minimize animation did not start');
retract.pause();
retract.currentTime = 260;
check(getComputedStyle(dock).clipPath !== 'none' && getComputedStyle(dock).translate !== 'none', 'Tape animation does not affect the dock');
el('.hide-btn').click();
check(dock.getAnimations().length === 1, 'Repeated click started overlapping animations');
retract.finish();
await retract.finished;
await Promise.resolve();
check(host.classList.contains('pill-mode') && !dock.inert, 'Minimize did not finish cleanly');
el('.floating-pill').click();
const extend = dock.getAnimations()[0];
check(!!extend, 'Expand animation did not start');
extend.finish();
await extend.finished;
await Promise.resolve();
check(!host.classList.contains('pill-mode') && !host.classList.contains('tape-transition') && !dock.inert, 'Expand did not restore the dock');
const report=document.createElement('pre');report.id='test-result';report.textContent='PASS: stable queue DOM, scroll and focus; queue filter, jump and playback; search race handling, clear, retry, keyboard navigation and focus; previous command and preview layout; skip buttons and single-toggle like/unlike animations.';document.body.append(report);
} catch(error) {const report=document.createElement('pre');report.id='test-result';report.textContent='FAIL: '+String(error);document.body.append(report);}

}
void run();
